const mongoose = require('mongoose');

//schema
const commentSchema = new mongoose.Schema({
    // mongoose.Schema.Types.ObjectId is a data type used to represent ObjectIds, which are unique identifiers generated by MongoDB for each document in a collection.
    post:{
        type: mongoose.Schema.Types.ObjectId,
        ref:"Post", //reference to the post model
    },
    user:{
        type:String,
        required: true,
    },
    body:{
        type:String,
        required:true,
    }

});

const Comment = mongoose.model('Comment', commentSchema);
module.exports = Comment;